services:
  v2board:
    image: ghcr.io/rebecca554owen/v2board:latest
    volumes:
      - ./:/www/
    restart: always
    network_mode: host
    ports:
      - "80:80"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    command: redis-server --unixsocket /data/redis.sock --unixsocketperm 777
    restart: unless-stopped
    volumes:
      - ./redis:/data  # /data/redis.sock 
    sysctls:
      net.core.somaxconn: 1024
