services:
  openppp2:
    image: ghcr.io/rebecca554owen/openppp2:latest
    container_name: openppp2
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./appsettings.json:/opt/appsettings.json
    network_mode: host
    environment:
      ENABLE_TC: "false"
      ENABLE_IO: "false"
      ENABLE_SIMD: "true"
      ENABLE_BYPASS: "true"
      BYPASS_COUNTRY: "CN"
      BYPASS_IPLIST_PATH: "/opt/ip.txt"
      BYPASS_REFRESH: "true"
      BYPASS_PULL_ON_START: "true"
    command: --mode=client --tun-host=no --tun-flash=yes --tun-ssmt=4/mq --tun-mux=0
