name: Build static binaries

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake zip libboost-coroutine-dev \
            libboost-context-dev libboost-filesystem-dev libboost-regex-dev \
            libboost-system-dev libboost-thread-dev libssl-dev libjemalloc-dev

      - name: Configure
        run: cmake -S . -B build-amd64 -DCMAKE_BUILD_TYPE=Release -DPPP_FORCE_STATIC=ON

      - name: Build
        run: cmake --build build-amd64 --target ppp -j$(nproc)

      - name: Inspect binary
        run: |
          file bin/ppp
          ldd bin/ppp || true

      - name: Package artifact
        run: |
          mkdir -p artifacts/linux-amd64
          cp bin/ppp artifacts/linux-amd64/ppp
          tar -czf openppp2-linux-amd64-static.tar.gz -C artifacts/linux-amd64 .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openppp2-linux-amd64-static
          path: openppp2-linux-amd64-static.tar.gz

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build on arm64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: |
            apt-get update
            apt-get install -y build-essential cmake zip libboost-coroutine-dev \
              libboost-context-dev libboost-filesystem-dev libboost-regex-dev \
              libboost-system-dev libboost-thread-dev libssl-dev libjemalloc-dev
          run: |
            cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build-arm64 -DCMAKE_BUILD_TYPE=Release -DPPP_FORCE_STATIC=ON
            cmake --build $GITHUB_WORKSPACE/build-arm64 --target ppp --parallel 1
            file $GITHUB_WORKSPACE/bin/ppp
            ldd $GITHUB_WORKSPACE/bin/ppp || true
            mkdir -p $GITHUB_WORKSPACE/artifacts/linux-arm64
            cp $GITHUB_WORKSPACE/bin/ppp $GITHUB_WORKSPACE/artifacts/linux-arm64/ppp
            tar -czf $GITHUB_WORKSPACE/openppp2-linux-arm64-static.tar.gz -C $GITHUB_WORKSPACE/artifacts/linux-arm64 .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openppp2-linux-arm64-static
          path: openppp2-linux-arm64-static.tar.gz
