name: build-openppp2-static

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '输入 openppp2 的 tag 名称'
        required: true
        default: 'v4.0.0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        platform:
          - linux/amd64
          - linux/aarch64
        ENABLE_IO: [true, false]
        ENABLE_SIMD: [true, false]
        exclude:
          - platform: linux/aarch64
            ENABLE_SIMD: true
        include:
          - platform: linux/amd64
            platform_name: linux-amd64
          - platform: linux/aarch64
            platform_name: linux-aarch64

    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      BOOST_VERSION: 1.86.0
      JEMALLOC_VERSION: 5.3.0
      OPENSSL_VERSION: 3.5.0

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Checkout openppp2 repository
      uses: actions/checkout@v4
      with:
        repository: liulilittle/openppp2
        path: openppp2
        ref: main

    - name: Get openppp2 tag
      id: get-tag
      run: |
        echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT

    - name: Validate parameters
      run: |
        PLATFORM=${{ matrix.platform_name }}
        if [[ -z "${PLATFORM}" ]]; then
          echo "错误：平台参数为空"
          exit 1
        fi

        # 定义构建文件名
        if ${{ matrix.ENABLE_IO }} && ${{ matrix.ENABLE_SIMD }}; then
          ARTIFACT_NAME=openppp2-${PLATFORM}-static-io-uring-simd.tar.gz
        elif ${{ matrix.ENABLE_IO }}; then
          ARTIFACT_NAME=openppp2-${PLATFORM}-static-io-uring.tar.gz
        elif ${{ matrix.ENABLE_SIMD }}; then
          ARTIFACT_NAME=openppp2-${PLATFORM}-static-simd.tar.gz
        else
          ARTIFACT_NAME=openppp2-${PLATFORM}-static.tar.gz
        fi
        echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV

    - name: Set THIRD_PARTY_LIBRARY_DIR environment variables
      run: |
        echo "THIRD_PARTY_LIBRARY_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Replace CMakeLists.txt with enhanced version
      run: |
        cd openppp2
        # 使用增强版本的 CMakeLists.txt
        cp $GITHUB_WORKSPACE/openppp/CMakeLists CMakeLists.txt

    - name: Replace THIRD_PARTY_LIBRARY_DIR in CMakeLists.txt
      run: |
        cd openppp2
        sed -i 's|SET(THIRD_PARTY_LIBRARY_DIR /root/dev)|SET(THIRD_PARTY_LIBRARY_DIR $ENV{THIRD_PARTY_LIBRARY_DIR})|' CMakeLists.txt

    - name: Enable IO_URING in CMakeLists.txt
      if: ${{ matrix.ENABLE_IO }}
      run: |
        cd openppp2
        sed -i 's|# IF(PLATFORM_SYSTEM_LINUX)|IF(PLATFORM_SYSTEM_LINUX)|' CMakeLists.txt
        sed -i 's|# *ADD_DEFINITIONS(-DBOOST_ASIO_HAS_IO_URING=1)|    ADD_DEFINITIONS(-DBOOST_ASIO_HAS_IO_URING=1)|' CMakeLists.txt
        sed -i 's|# *ADD_DEFINITIONS(-DBOOST_ASIO_DISABLE_EPOLL=1)|    ADD_DEFINITIONS(-DBOOST_ASIO_DISABLE_EPOLL=1)|' CMakeLists.txt
        sed -i 's|# ENDIF()|ENDIF()|' CMakeLists.txt
        sed -i 's|# *liburing.a|liburing.a|g' CMakeLists.txt

    - name: Enable SIMD in CMakeLists.txt
      if: ${{ matrix.ENABLE_SIMD }}
      run: |
        cd openppp2
        sed -i 's|SET(__SIMD__ FALSE)|SET(__SIMD__ TRUE)|' CMakeLists.txt

    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v4
      with:
        path: boost
        key: ${{ matrix.platform }}-${{ matrix.os }}-boost-${{ env.BOOST_VERSION }}

    - name: Cache Jemalloc
      id: cache-jemalloc
      uses: actions/cache@v4
      with:
        path: jemalloc
        key: ${{ matrix.platform }}-${{ matrix.os }}-jemalloc-${{ env.JEMALLOC_VERSION }}

    - name: Cache OpenSSL
      id: cache-openssl
      uses: actions/cache@v4
      with:
        path: openssl
        key: ${{ matrix.platform }}-${{ matrix.os }}-openssl-${{ env.OPENSSL_VERSION }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake
        if ${{ matrix.ENABLE_IO }}; then
          sudo apt-get install -y liburing-dev
        fi

    - name: Build boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        BOOST_VERSION_UNDERSCORE=$(echo ${{ env.BOOST_VERSION }} | sed 's/\./_/g')
        wget https://archives.boost.io/release/${{ env.BOOST_VERSION }}/source/boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2
        tar jxvf boost*.tar.bz2
        rm -rf boost*.tar.bz2
        mv boost* boost
        cd boost
        ./bootstrap.sh
        ./b2 cxxflags=-fPIC

    - name: Build jemalloc
      if: steps.cache-jemalloc.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/jemalloc/jemalloc/releases/download/${{ env.JEMALLOC_VERSION }}/jemalloc-${{ env.JEMALLOC_VERSION }}.tar.bz2
        tar jxvf jemalloc*.tar.bz2
        rm -rf jemalloc*.tar.bz2
        mv jemalloc-* jemalloc
        cd jemalloc
        ./autogen.sh --with-jemalloc-prefix=je_
        make -j $(nproc)

    - name: Build openssl
      if: steps.cache-openssl.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/openssl/openssl/releases/download/openssl-${{ env.OPENSSL_VERSION }}/openssl-${{ env.OPENSSL_VERSION }}.tar.gz
        tar zxvf openssl*.tar.gz
        rm -rf openssl*.tar.gz
        mv openssl* openssl
        cd openssl
        ./Configure
        make -j $(nproc)

    - name: Build openppp2 static
      run: |
        cd openppp2
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DPLATFORM_SYSTEM_LINUX=ON \
                -DPPP_FORCE_STATIC=ON
        make -j $(nproc)

    - name: Inspect binary
      run: |
        file openppp2/bin/ppp
        ldd openppp2/bin/ppp || true

    - name: Package openppp2 static
      run: |
        mkdir -p artifacts/${{ matrix.platform_name }}
        cp openppp2/bin/ppp artifacts/${{ matrix.platform_name }}/ppp
        tar -czf ${{ env.ARTIFACT_NAME }} -C artifacts/${{ matrix.platform_name }} .

    - name: Upload openppp2 static
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_NAME }}

    - name: Record build time
      run: |
        echo "BUILD_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2.4.1
      with:
        files: ./*.tar.gz
        tag_name: ${{ steps.get-tag.outputs.tag }}
        body: |
          Static Build Release: ${{ env.BUILD_TIME }}

          ## 构建配置
          - 平台: ${{ matrix.platform_name }}
          - IO_URING: ${{ matrix.ENABLE_IO }}
          - SIMD: ${{ matrix.ENABLE_SIMD }}
          - 静态链接: 是
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}