name: build-openppp2-docker # push docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '输入 openppp2 版本标签,默认为最新版'
        required: true
        default: 'v2.7.0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/openppp2

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            platform_name: linux-amd64
          - platform: linux/arm64
            platform_name: linux-arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        id: get-tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "push" ] && [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=v1.0.0" >> $GITHUB_OUTPUT
          fi

      - name: Validate Docker tag
        run: |
          tag="${{ steps.get-tag.outputs.tag }}"
          if [[ "$tag" != "latest" && ! "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "错误：标签格式无效，应为v*.*.*或latest"
            exit 1
          fi

      - name: Build and push platform-specific images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./openppp/ppp.Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ steps.get-tag.outputs.tag }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-tag.outputs.tag }}

      - name: Save digest
        shell: bash
        run: |
          mkdir -p /tmp/digests
          DIGEST=$(docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-tag.outputs.tag }} --format '{{json .Manifest.Digest}}')
          echo $DIGEST > /tmp/digests/${{ matrix.platform_name }}

      - name: Upload digests
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.platform_name }}
          path: /tmp/digests
          retention-days: 1

  merge:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          pattern: digests-*
          path: /tmp/digests
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag }}
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          DOCKER_TAGS=$(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")
          
          DIGEST_AMD64=$(cat linux-amd64 | tr -d '"')
          DIGEST_ARM64=$(cat linux-arm64 | tr -d '"')

          docker buildx imagetools create $DOCKER_TAGS \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@$DIGEST_AMD64 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@$DIGEST_ARM64
      
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }}
